# Generated by Django 5.2 on 2025-04-13 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogCategoryModel',
            new_name='BlogCategory',
        ),
    ]
