# Generated by Django 5.2 on 2025-04-24 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogcategory_image_alter_article_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='image',
        ),
    ]
