# Generated by Django 5.2 on 2025-06-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_article_meta_description_article_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Publish Date'),
        ),
    ]
