# Generated by Django 5.2 on 2025-05-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.CharField(verbose_name=255)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Price')),
                ('created_at', models.DateTimeField(verbose_name='Created')),
                ('updated_at', models.DateTimeField(verbose_name='Updated')),
            ],
        ),
    ]
