# Generated by Django 5.2 on 2025-05-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_product_meta_description_product_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(unique=True, verbose_name='Slug'),
        ),
    ]
