# Generated by Django 5.2 on 2025-06-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
