# Generated by Django 5.2 on 2025-06-18 09:58

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='text',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Content'),
        ),
    ]
