# Generated by Django 5.2 on 2025-06-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_product_user'),
        ('main', '0002_alter_page_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='Sort')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activated')),
                ('products', models.ManyToManyField(to='catalog.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Carousel',
                'verbose_name_plural': 'Products Carousel',
                'ordering': ['sort'],
            },
        ),
    ]
